package id.holigo.services.common;

public enum PaymentStatusEnum {
    SELECTING_PAYMENT ,WAITING_PAYMENT, VERIFYING_PAYMENT, PAYMENT_FAILED, PAID, PAYMENT_CANCELED, PAYMENT_EXPIRED, PROCESS_REFUND,
    WAITING_REFUND, REFUNDED
}
